### ISSUE TITLE
[Umbrella Issue] Refactor Application to deploy resources directly without AppContext layer

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1705]
Currently the Application object(OAM v0.3) still relies on AppContext which is actually AppConfig(OAM v0.2).
As we want to make KubeVela as control plane, we should refactor the Application controller and remove the dependency of AppContext.

## Here's the working items that we have to finish:

- [ ] 1. AppRollout should not rely on AppContext and should be able to work in runtime cluster. #1605
- [x] 2. generate/set name&namespace of workload/trait instances in Application
- [x] 3. set workload reference to trait (TraitDefinition WorkloadRefPath) in Application
- [x] 4. add workload reference to scope (scope feature) in Application
- [x] 5. enable trait system still works on helm-based workload when workload type is given and not rely on AppContext
- [x] 6. controller-owner references of workload/trait instances should be Application instead of AppContext
- [x] 7. add a series of Label/Annotation to workload/trait instances in Application
- [x] 8. convert useful webhook logic in AppConfig to Application
- [x] 9. After all the above was done, let's remove the AppContext dependency in Application Controller.
- [x] 10. package the AppConfig based controller in a separated helm chart #1305
- [x] 11. backward compatibility test (upgrade clusters in each version v1.0.0, ..., v1.0.6)

## Features that contained in AppConfig but different in Application:

1. [DAG-based dependency(data input and output)](https://github.com/crossplane/oam-kubernetes-runtime/blob/master/design/resource-dependency.md): this should be replaced by [workflow](https://github.com/oam-dev/kubevela/blob/master/design/vela-core/workflow_policy.md).

## Features that should be evaluated

The following features work in AppConfig but not have clear use cases, we should evaluate and hold until we have real use cases:

1. [apply-once-only mechanism](https://github.com/oam-dev/kubevela/blob/master/design/vela-core/apply-once-only.md): it works for use cases which the OAM controller should cooperate with others and do not control after deployed. 
2. [component-level revision mechanism](https://github.com/crossplane/oam-kubernetes-runtime/blob/master/design/one-pager-component-mutable-and-versioning.md): in Application of KubeVela, we have AppRevision which records the whole Application, so we don't seem to see there's cases that still need the component level revision.

**Comment by captainroy-hy** [comment]
Here is a basic proposal for the logic workflow of app controller after refactor. The core opinion is aggregating closely-relevant logic into independent and reusable modules.
Accordingly, the logic of app controller is generally divided into several phases as shown below.

#### 1. render phase
- generate appfile from application
- generate ac & comps from appfile (let's call these resources as raw manifests)

This phase can be re-used by validating-webhook.

#### 2. revision phase
- create/update & get components revision (must do it in this phase)
- compute AppRevision hash based on app spec and appfile's subs
- record raw manifests into AppRevision
- create/update AppRevision and get revision

This phase can be re-used by `apply-once-only` mechanism in the future.

#### 3. assemble phase (most refactor work happens here)
- generate name/ns for manifests
- set labels/annots for manifests
- set workload reference to traits&scopes
- set owner references for manifests
- handle `ResourceTracker`

After this phase, raw manifests become assembled manifests, which means they are ready to go. This phase can be re-used by rollout controller.

#### 4. dispatch phase
- apply assembled manifests into vela control-plane cluster
- (TBD) dispatch to runtime clusters through OCM

#### 5. GC phase 
Same logic as AppConfig controller does now

#### 6. embedded rollout phase
(TBD) depends on refactor works on rollout

#### 7. health-check phase
Stay unchanged in this refactor.

#### And there are two finalizing logics
- finalize `ResourceTracker` (maybe no need)
- de-reference workloads from scopes

/cc @wonderflow @wangyikewxgm

**Comment by wonderflow** [comment]
@captainroy-hy LGTM

**Comment by wangyikewxgm** [comment]
@captainroy-hy Agree with you, our current AppDeploy controller logic implement duplicating apply logic.After refactor in the feature App AppRollout and AppDeployment could use same serial functions.

**Comment by hongchaodeng** [comment]
> record raw manifests into AppRevision

@captainroy-hy 
In PR https://github.com/oam-dev/kubevela/pull/1708, I also add a `resources` in AppRev which includes rendered resources including Comps, Traits, Policies.

**Comment by captainroy-hy** [comment]
> > record raw manifests into AppRevision
> 
> @captainroy-hy
> In PR #1708, I also add a `resources` in AppRev which includes rendered resources including Comps, Traits, Policies.

Got it. @hongchaodeng Thx for reminding! I will check that.

**Comment by captainroy-hy** [comment]
After removing AppCtx, we need someone to do GC jobs. An idea is to encapsulate GC logic into `dispatch phase`, the same place where we emit resources into clusters. And we can employ `ResourceTracker` into `dispatch phase`. `ResourceTracker` will record the resources applied into the clusters. 

#### Here's a basic workflow of `dispatch phase`.

- input an array of resources, an `AppRevision`, and a reference of `ResourceTracker`(it could be optional)
- if input `RT` is nil (it's the same one created last time), apply resources, create a new `RT` and record the resource references  in it, return the newly created `RT`
  - add new `RT` as the owner of all resources;  add App as the owner of `RT`
  - `RT` should be named in a fixed format: `<AppRevisionName> + <Namespace>` (with help of this, rollout controller can avoid adding new fields to record `RT` references)
- if input `RT` is not nil, it means the caller wanna GC  besides emitting resources. 
- GC logic will compare input resources and ones recorded in the input `RT`
  - for new one, emit it into clusters
  - for removed one, delete it from clusters
  - for unchanged ones, update their owner to new `RT`

Based on that, `assemble phase` and `dispatch phase` play a stand-alone role capable of serving different controllers as shown in the figure.
`ResourceTracker` controller is related to other features mentioned in #1719 and has nothing to do with this refactor work.

![image](https://user-images.githubusercontent.com/5107364/120131034-7b57b200-c202-11eb-9483-6e7f0f3d8a96.png)
