### ISSUE TITLE
Refine KubeVela add-on support and extend Terraform typed ComponentDefinitions

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#1770]
# Background
As more and more developers are contributing to [Terraform Kubernetes controller](https://github.com/oam-dev/terraform-controller), Alibaba Cloud, AWS, Azure, GCP, and VMware vSphere are supported. We plan to refine the KubeVela add-on support to help install Terraform controller chart in a simple way. At the same time, we plan to extend the number of supported Terraform ComponentDefinitions to 50, across those cloud providers.

# Tasks

- [x] Install Terraform controller chart as a system add-on @chivalryq https://github.com/oam-dev/kubevela/issues/1760
- [ ] Prepare a registry folder to put in Terraform types ComponentDefinitions @chivalryq 
- [ ] 30 Terraform ComponentDefinitions for Alibaba Cloud @chivalryq @zzxwill 
- [ ] 10 Terraform ComponentDefinitions for AWS @chivalryq @zzxwill 
- [ ] 10 Terraform ComponentDefinitions for Azure Cloud @chivalryq @zzxwill 
- [ ] some Terraform ComponentDefinitions for GCP, vSphere or others @chivalryq @zzxwill

**Comment by barnettZQG** [comment]
Based on cloud services commonly used in application management latitudes, The following supporting suggestions are made:

## Service As Component

Service | Provider | Description
-- | -- | --
RDS MYSQL | Aliyun\AWS\Azure\Google\华为云\腾讯云 |  
RDS PG | Aliyun\AWS\Azure\Google\华为云\腾讯云 |  
RDS SqlServer | Aliyun\AWS\Azure\Google\华为云\腾讯云 |  
Redis | Aliyun\AWS\Azure\Google\华为云\腾讯云 | Amazon ElastiCache
MongoDB | Aliyun\AWS\华为云\腾讯云 | Amazon DocumentDB
Hbase | Aliyun |  
DynamoDB | AWS |  
Elasticsearch | Aliyun\ |  
实时计算 Flink 版 | Aliyun\ |  
OSS 对象存储服务 | Aliyun\AWS\Azure\Google\华为云\腾讯云 |  
消息队列 RocketMQ 版 | Aliyun\华为云 |  
消息队列 RabbitMQ 版 | Aliyun\华为云 |  
微消息队列 MQTT 版 | Aliyun\ |  
ActiveMQ | AWS | Amazon MQ


## Service As Trait

Prometheus 监控服务 | Aliyun |  
-- | -- | --
SLS 日志服务 | Aliyun |  
  |   |  


## Service As Infra

Kubernetes | Aliyun\AWS\Azure\Google\华为云\腾讯云 |  
-- | -- | --
SLB | Aliyun\AWS\Azure\Google\华为云\腾讯云 |  
  |   |
