### ISSUE TITLE
Umbrella issue for vela MVP

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#198]
# Goal

1. Setup a WordPress app with database as demo
2. choose web-service workload will result to an url which can directly access this app
3. rolling upgrade with traffic split
4. metric to grafana monitoring

# Vela Core

- [x] 1. clean up readme
- [x] 1. Initialize vela core and integrate existing workloads/traits #199  @ryanzhang-oss 
- [x] 2. Create  web-service/back-end/job  as core workload. #197 @ryanzhang-oss 
- [ ] 3. vela cli run web-service/back-end/job (cue template)     `vela run comp --ky k=v --ky k1=v2`
- [x] 4. support api gateway as domain/dns/route trait for web service application #175  @wonderflow 
- [x] 5. (this also need to build a helm chart for vela core) @ryanzhang-oss 
- [x] 6. `oam system init` (`oam install`) install vela core instead of oam-k8s-runtime.   #226
- [x] 7. put cert-manager into vela core and enable webhook by default. #228  @ryanzhang-oss 
- [x] 8. auto scale [keda](https://github.com/kedacore/keda) @zzxwill 
- [ ] 9.  support traffic management for rolling update different versions of an app  #172 @wonderflow 

# Vela CLI

- [x] 1. support `vela logs` for digging logs from workload #161   @zzxwill 
- [ ] 2. vela exec <appname> entering the process #171  @zzxwill 
- [x] 3.  refine output for `vela app status` #150  @wonderflow 
- [x] 4. refine the output of `vela app ls` @wonderflow 
- [x] 5. `vela comp ls`  `vela comp delete` @wonderflow 
- [x] 6. `vela app init`   , and we must init app before comp run.

# UX 

- [ ] 1. Dashboard @hanxie-crypto 
- [ ] 2. Source to image,  https://github.com/openshift/source-to-image

---

**Comment by resouer** [comment]
Please ensure all server side tasks have higher priority.

**Comment by wonderflow** [comment]
@resouer  I'm not sure if source-to-image is a high priority issue, though I propose it the first day #14

**Comment by hongchaodeng** [comment]
The README is still missing how to add capabilities via CLI, which is already implemented.
This is highly important IMO.

**Comment by resouer** [comment]
@wonderflow source-to-image is a must have IMO. And we can make it work easily by integrating with existing tools as a start.

**Comment by resouer** [comment]
Cron as a trait is charming but it would very hard to implement actually. I think we may want to leave it as CronJob at day 1.

**Comment by resouer** [comment]
@wonderflow @zzxwill One app multiple components is still missing in cli/dashboard, this should be included in day 1 release.

**Comment by wonderflow** [comment]
Closing as we prefer #420
