### ISSUE TITLE
Umbrella issue for vela Dashboard/API

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#231]
# Environment
- [x] create/update an env @wenxinnnnn 
- [x] list envs @wenxinnnnn @hanxie-crypto @woshilanren11
- [x] switch an env @hanxie-crypto @woshilanren11
- [x] delete an env @wenxinnnnn 

# Application
### create
- [x] create application (run workload and attach trait)
- [x] hidden/remove name parameter in settings when running a workload #225 @woshilanren11
### list
- [x] basic listing apps @hanxie-crypto @woshilanren11
- [x] sort application list in inverse order of created time
- [x] workload name is missing in app list @woshilanren11
### delete
- [x] [dashboard] delete an application @woshilanren11
- [x] [api] delete an application #233 @wenxinnnnn 
### detailes
- [x] describe workloads/traits @woshilanren11
- [x] attach one or more traits @woshilanren11
- [x] detach trait @woshilanren11

# Workloads
- [x] list newly added (synchronized) capability #191 @woshilanren11
- [x] run workload and attach trait @woshilanren11
- [x] [LowPriority] support identity workload/trait icon #229

# Traits
- [x] list newly added (synchronized) capability #191 @woshilanren11
- [x] run workload and attach trait @woshilanren11

# Capability
## capability center
- [x] add/sync/list capability center @woshilanren11
- [x] [api] implement deleting capability center #218 #219 @mosesyou 
## capabilities
- [x] add/remove/ls capabilities @hanxie-crypto @woshilanren11
