### ISSUE TITLE
[Umbrella Issue]: CLI Update and Improvements

### ISSUE THREAD

**Issue by chivalryq** [oam-dev/kubevela#2438]
Here are something should be cleaned up in vela CLI and vela kubectl plugin.

- [ ] 1. unify two tools, which means they have the same function and implementation.
- [x] 2. deprecate operations related with `vela cap`, use `comp`/`trait` command in kubectl plugin （#2346）
- [x] 3. now `comp`/`trait` command receive a flag "--registry", we should make regisry URL cached in local and user can use by name.
- [x] 4. now `components`/`traits`  in vela CLI means show definitions installed in cluster and we should merge them with `comp`/`trait` command in kubectl plugin. It's expected that `comp`/`trait` command can 1. show installed definitions 2. show definitions in registry 3. install/uninstall a definition
- [ ] 5. appfile support 1.1 feature
- [ ] 6. support better debug measures, 
	- [x] `vela status` should be updated. There is a bug for non-default namespace app. Also, more info should be exposed (workflow, event...) 
	- [x] `vela logs` support multicluster
	- [x] `vela exec` support multicluster
New features wanted
1. vela secret #31 
2. use vela to debug #2406 
3. use vela to init addon template #2112 
4. support X-definition versioning (This is important because if there are imcompatible X-definition, we should make sure user can get older definition.)
5. support addon versioning
6. consider more continuous delivery situation for `vela up`

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
