### ISSUE TITLE
[BUG] Umbrella issue for KubeVela Dashboard

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela#266]
# Application
### detail
- [ ] provide application logs function to see logs of pods #263
- [ ] provide application exec function to login a container #264

### create
- [ ] refine creation UX @hanxie-crypto 

### Component
- [ ] design and implement components operations
- [ ] [API] implement component operations related API

### Workloads/Traits
- [ ] [API] List more parameters and catalog them for core workloads and traits #265 @zzxwill
