### ISSUE TITLE
Umber Issue Before Kubecon Release

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#420]
# Vela-Core

- [ ] 1. Auto Scaler
- [ ] 2. Rolling Update
- [ ] 3. Job 

# Vela CLI

- [ ] 1. App Centric Story issues: https://github.com/oam-dev/kubevela/issues/399
- [x] 2. Refactor and Align terms for core concept enhancement  #412
- [ ] 3. Refactor 'vela up' dependency 'docker', 'kubectl','kind'  #413
- [ ] 4. end to end demos (appfile + CLI)
  - [x]    4.1 webservice + route that app could be visited after deploy
  - [ ]    4.2 rolling update with canary trait
  - [ ]    4.3 autoscale demo with autoscaling trait
- [ ] 5. Tutorials
  - [ ]    5.1 normal deploy with CLI/Appfile
  - [ ]    5.2 do operations with trait by CLI or update Appfile
  - [ ]    5.3 plugin systems.
  - [ ]    5.4 how to write a custom capability(workload/trait)
- [x]  6.  refactor all commands to be app centric #322

**Comment by wonderflow** [comment]
Closing as it's all done
