### ISSUE TITLE
[Feature] Complete new structure of documentation site.

### ISSUE THREAD

**Issue by resouer** [oam-dev/kubevela#441]
**Overview**

- [x] - [Introduction](introduction.md) @resouer 
- [x] - [Installation](https://github.com/oam-dev/kubevela/blob/master/docs/install.md) @hongchaodeng 
- [x] - [Quick Start](quick-start.md) @hongchaodeng  
- [x] - [Concepts](concepts.md) @resouer 

**For Developers**

- [x] - [Setting Up Deployment Environment](developers/config-enviroments.md) @wonderflow     
- [x] - [Initializing Application](developers/deploy-app.md) @hongchaodeng 
- [x] - [Setting Routes](developers/set-route.md) @wonderflow 
- [x] - [Setting Auto-scaling Policy](developers/set-autoscaling.md) @zzxwill 
- [x] - [Setting Rollout Strategy](developers/set-rollout.md) @wonderflow 
- [x] - [Monitoring Application](developers/set-metrics.md) @wonderflow 
- [x] - [Using Appfile](developers/devex/appfile.md) @hongchaodeng 
- [x] - [Execute Commands in Container](developers/exec-cmd.md) @hongchaodeng 
- [x] - [Check Application Logs](developers/check-logs.md) @hongchaodeng 
- [x] - [Port forward to container](developers/port-forward.md) @hongchaodeng 
- [x] - [Configuring Application](developers/config-app.md) @hongchaodeng 
- [x] - [Consuming Cloud Services](developers/cloud-service.md) @szihai 
- [x] - [Reference Docs](https://github.com/oam-dev/kubevela/tree/master/docs/developers/references) should be generated from CUE templates but we could fill them manually for now, /assign @hongchaodeng 

**For Platform Engineers**

- [x] - [Extending KubeVela](platform-engineers/extending-kubevela.md) @hongchaodeng  

**Internals**

- [x] - [Design and Architecture](design.md) Already Done!

**Roadmap**

- [x] - [Roadmap of KubeVela](roadmap.md) @resouer 

/cc @Fei-Guo

**Comment by hongchaodeng** [comment]
Suggested change: Configuring Deployment Environment -> Setting up deployment environment

As a side note, we also need to document installing capabilities services including:
- Prometheus & Grafana
- Flagger
- Nginx Ingress
- KEDA

**Comment by resouer** [comment]
> As a side note, we also need to document installing capabilities services including:

Let's put this section as part of `docs/install.md`, and let user know:

1. Those dependencies will be installed automatically in his cluster during `vela install`.
2. If they have installed their own version, how to skip certain dependency in `vela install`.

The Nginx Ingress is kinda special, I don't think vela install will handle it, so user must enable it manually (that's why I added a section in `docs/install.md` as well). /cc @wonderflow

**Comment by hongchaodeng** [comment]
> The Nginx Ingress is kinda special, I don't think vela install will handle it, so user must enable it manually 

We should use discovery client to detect both API resources and their controllers (deployments).

**Comment by hongchaodeng** [comment]
A Reference on how OLM manages dependency services via InstallPlan: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/architecture.md#catalog-operator

**Comment by hongchaodeng** [comment]
> Reference Docs should be generated from CUE templates but we could fill them manually for now, /assign @hongchaodeng

ref: https://github.com/oam-dev/kubevela/issues/492

**Comment by wonderflow** [comment]
@hongchaodeng  @resouer things are almost done, let's go through the whole doc again and check if they're all ready.

**Comment by wonderflow** [comment]
Closing, as it's done
