### ISSUE TITLE
[Feature] fix TODO(nolint:golint) for #614

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#645]
In #614 I found too many golint complains according to our golangci check strategy, I have fixed lots of them but there're still many lint errors left, I hope someone else could help fix them. 

Remove one  TODO(nolint:golint) for one PR is fine.

**Comment by horis233** [comment]
### Files with `/nolint:golint`

- [ ] ./pkg/commands/dashboard.go
- [ ] ./pkg/commands/env.go
- [ ] ./pkg/commands/exec.go
- [ ] ./pkg/commands/init.go
- [ ] ./pkg/commands/logs.go
- [ ] ./pkg/commands/ls.go
- [ ] ./pkg/commands/status.go
- [ ] ./pkg/commands/system.go
- [ ] ./pkg/commands/template.go
- [ ] ./pkg/commands/trait.go
- [ ] ./pkg/commands/traits.go
- [ ] ./pkg/commands/up.go
- [ ] ./pkg/commands/workloads.go
- [ ] ./pkg/controller/v1alpha1/autoscaler/types.go
- [ ] ./pkg/server/appHandlers.go
- [ ] ./pkg/server/capabilityHandlers.go
- [ ] ./pkg/server/componentHandlers.go
- [ ] ./pkg/server/envHandlers.go
- [ ] ./pkg/server/scopeHandlers.go
- [ ] ./pkg/server/traitHandler.go
- [ ] ./pkg/server/util/api.go
- [ ] ./pkg/server/util/middleware.go

Please use the above tracking list for everyone who is going to contribute to avoid duplicate works.
  - When you are going to fix the lint error, please append your GH id after the file, like 
     
     - [ ] ./pkg/commands/dashboard.go @horis233
     
  - After the lint issue is fixed, then tick the checkpoint

### Steps to fix a lint issue

Step1: Remove `/nolint:golint` from one file in the above list.
Step2: Run `make lint` and check the logged errors
Step3: Fix errors by following the message and ensure `make lint` is clean
Step4: File a PR and ref this https://github.com/oam-dev/kubevela/issues/645: Ref #645

**Comment by laojianzi** [comment]
- [ ] ./pkg/commands/init.go @laojianzi

**Comment by wonderflow** [comment]
#659 fixed some of them @captainroy-hy  can you help list the left here?

**Comment by wonderflow** [comment]
#664

**Comment by wonderflow** [comment]
closing as it's all fixed now, thanks so much @horis233 @laojianzi @captainroy-hy
