### ISSUE TITLE
[Feature] Merging oam-runtime into vela-core

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#657]
- [x] standardize kubevela project structure #660 
- [x] Merge oam-runtime Code into KubeVela  #657 
- [ ] Add startup parameters for vela-core that could allow vela-core run oam-runtime framework only, disable core workloads traits. https://github.com/oam-dev/kubevela/issues/658
- [ ] Add a migrate guide.
