### ISSUE TITLE
Umbrella issue for KubeVela 1.0

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#932]
We're going to release [KubeVela v1.0 Preview Version](https://github.com/oam-dev/kubevela/milestone/3) in mid or end of March.

In this release, we're going to give our user especially platform builders a stable user interface(UI) and user experience(UX). A stable UI/UX can help the community grow faster and better. Also, we will show more community integration capability.

Here are the issues I'm going to add into KubeVela 1.0, open for discussion.

# User interfaces for platform builders

- [x] *  Application object as the deployment unit applied to k8s control plane.
            1. The new Application object will handle CUE template rendering on the server side. So the appfile would be translated to Application object directly without doing client side rendering.
            2. CLI/UI will be updated to replace ApplicationConfiguration and Component objects with Application object.
- [x] * [AppRollout object](https://github.com/oam-dev/kubevela/blob/master/design/vela-core/rollout-design.md) for progressive application rollout.
- [ ] * [Package and Catalog](https://github.com/oam-dev/kubevela/blob/master/design/vela-core/APIServer-Catalog.md#3-catalog-design) for platform capability center and a unified storage format.
- [ ] * Documentation and examples to introduce all of these objects and their usage.
- [x] * Final version of definition objects

# Community integration

- [ ] * integrate with terraform by building a server side operator. We have done a [client side PoC](https://github.com/oam-dev/kubevela/pull/863), we need to build a server side CRD operator so that the platform builder can integrate with KubeVela better.
- [x] * [integrate with helm](https://github.com/oam-dev/kubevela/issues/864) will not include in KubeVela 1.0, but we need a detail design doc.

# UX for end users

- [x] * CLI and Appfile should integrate with Application instead of AppConfig and Component.
- [ ] * CLI and Appfile should support ApplicationDeployment Rollout.
- [ ] * [Formally release our dashboard](https://github.com/oam-dev/kubevela/issues/740).
- [x] * platform builder install step refactor, from `vela install` to `helm install`

# Issues List

All issues will be marked as [KubeVela-v1.0 milestone](https://github.com/oam-dev/kubevela/milestone/3), you can view all the issues in the milestone and know the progress of it.

**Comment by resouer** [comment]
The general roadmap LGTM. A side note for what will be released from user (platform builder) perspective:

![image](https://user-images.githubusercontent.com/1701782/105765872-e409e780-5f0d-11eb-83a4-84fc5c036875.png)

The standard contract is important for building interoperability between `Application` and operation.

**Comment by lxd5866** [comment]
How is the terraform integration work going on now?

**Comment by wonderflow** [comment]
@zzxwill  is working on that, we're planning to create a new controller for terraform. https://github.com/oam-dev/kubevela/issues/1128
